use geo;
-- Create table CNEFE
CREATE TABLE CNEFE (
  COD_UNICO_ENDERECO 	VARCHAR(10),
  COD_SETOR 	VARCHAR(17),
  NUM_QUADRA 	VARCHAR(2),
  NOM_TIPO_SEGLOGR 	VARCHAR(20),
  NOM_TITULO_SEGLOGR 	VARCHAR(50),
  NOM_SEGLOGR 	VARCHAR(50),
  NUM_ENDERECO 	VARCHAR(10),
  NOM_COMP_ELEM1 	VARCHAR(20),
  VAL_COMP_ELEM1 	VARCHAR(20),
  CEP 	VARCHAR(9),
  LATITUDE 	FLOAT,
  LONGITUDE 	FLOAT,
  NUM_FACE 	VARCHAR(2),
  COORDENADAS 	geometry,
  CONSTRAINT pk_CNEFE PRIMARY KEY (COD_UNICO_ENDERECO)
);
