SELECT 
    L.COD_MUNICIPIO,
    R.SC_ID_LOGRADOURO,
    R.CI_NOM_LOGRADOURO,
    R.CI_NOM_LOGRADOURO_NORM,
    COUNT(L.COD_UNICO_ENDERECO) AS QTD_LOTES
FROM CI_LOTES L
INNER JOIN CI_LOGRADOUROS R 
    ON L.NOM_LOGRADOURO = R.CI_NOM_LOGRADOURO 
    AND L.COD_MUNICIPIO = R.COD_MUNICIPIO
GROUP BY 
    L.COD_MUNICIPIO, 
    R.SC_ID_LOGRADOURO, 
    R.CI_NOM_LOGRADOURO,
    R.CI_NOM_LOGRADOURO_NORM
ORDER BY QTD_LOTES DESC;