SELECT 
    L.COD_MUNICIPIO,
    R.SC_ID_LOGRADOURO,
    R.CI_NOM_LOGRADOURO,
    R.CI_NOM_LOGRADOURO_NORM,
    COUNT(L.COD_UNICO_ENDERECO) AS QTD_LOTES
FROM CI_LOTES L
INNER JOIN CI_LOGRADOUROS R 
    ON L.NOM_LOGRADOURO = R.CI_NOM_LOGRADOURO 
    AND L.COD_MUNICIPIO = R.COD_MUNICIPIO
GROUP BY 
    L.COD_MUNICIPIO, 
    R.SC_ID_LOGRADOURO, 
    R.CI_NOM_LOGRADOURO,
    R.CI_NOM_LOGRADOURO_NORM
ORDER BY QTD_LOTES DESC;

SELECT 
--    L.NUM_QUADRA,
    DISTINCT L.NOM_LOGRADOURO
--    R.CI_NOM_LOGRADOURO_NORM,
--    L.NUM_ENDERECO,
--    L.DIM_TESTADA,
--    L.DIM_PROFUNDIDADE,
--    L.AREA,
--    L.COD_UNICO_ENDERECO
FROM CI_LOTES L
INNER JOIN CI_LOGRADOUROS R 
	ON L.NOM_LOGRADOURO = R.CI_NOM_LOGRADOURO COLLATE latin1_swedish_ci
    AND L.COD_MUNICIPIO = R.COD_MUNICIPIO
WHERE 
    R.SC_ID_LOGRADOURO IS NULL
    AND R.CI_NOM_LOGRADOURO IN (
        'RUA ARARUNA', 'RUA ANAJE', 'RUA XINGU', 'RUA GENTIL ALCHIERI', 
        'RUA DORVAL BENATTI', 'RUA VILMAR BERFT', 'RUA CEREJEIRA', 
        'RUA GUAJUVIRA', 'RUA REINALDO LINDEN', 
        'RUA DAS PEROBAS', 'AVENIDA DAS FLORES', 'RUA HERMINIA BARBIERI BIGATON', 
        'RUA CEDRO', 'RUA CARLOS MAGRO', 'RUA LOURO BRANCO', 
        'RUA CAMELIA', 'RUA PITANGUEIRA', 'RUA DELMAR SEVERO', 'RUA EUGENIO RAVACHE', 'RUA JOAO MARTINI'
    )
ORDER BY L.NOM_LOGRADOURO, L.NUM_ENDERECO;

WITH Lista_Busca AS (
    SELECT 'RUA ARARUNA' AS nome UNION ALL SELECT 'RUA ANAJE' AS nome UNION ALL
    SELECT 'RUA XINGU' AS nome UNION ALL SELECT 'RUA GENTIL ALCHIERI' AS nome UNION ALL
    SELECT 'RUA DORVAL BENATTI' AS nome UNION ALL SELECT 'RUA VILMAR BERFT' AS nome UNION ALL
    SELECT 'RUA CEREJEIRA' AS nome UNION ALL SELECT 'RUA GUAJUVIRA' AS nome UNION ALL
    SELECT 'AVENIDA MAUA' AS nome UNION ALL SELECT 'RUA REINALDO LINDEN' AS nome UNION ALL
    SELECT 'RUA DAS PEROBAS' AS nome UNION ALL SELECT 'AVENIDA DAS FLORES' AS nome UNION ALL
    SELECT 'RUA HERMINIA BARBIERI BIGATON' AS nome UNION ALL SELECT 'RUA CEDRO' AS nome UNION ALL
    SELECT 'RUA CARLOS MAGRO' AS nome UNION ALL SELECT 'RUA LOURO BRANCO' AS nome UNION ALL
    SELECT 'RUA CAMELIA' AS nome UNION ALL SELECT 'RUA PITANGUEIRA' AS nome UNION ALL
    SELECT 'RUA DELMAR SEVERO' AS nome UNION ALL SELECT 'RUA EUGENIO RAVACHE' AS nome
)
SELECT 
    B.nome AS logradouro_pesquisado,
    CASE 
        WHEN R.CI_NOM_LOGRADOURO IS NULL THEN '❌ NÃO ENCONTRADO'
        ELSE '✅ ENCONTRADO'
    END AS status_no_sistema,
    COUNT(L.COD_UNICO_ENDERECO) AS qtd_lotes_vinculados
FROM Lista_Busca B
LEFT JOIN CI_LOGRADOUROS R 
    ON B.nome = R.CI_NOM_LOGRADOURO COLLATE latin1_swedish_ci
    AND R.SC_ID_LOGRADOURO IS NULL
LEFT JOIN CI_LOTES L 
    ON R.CI_NOM_LOGRADOURO = L.NOM_LOGRADOURO COLLATE latin1_swedish_ci
GROUP BY B.nome
ORDER BY status_no_sistema DESC, B.nome ASC;