SELECT * FROM smuu.CI_ADJACENTES;

DELETE FROM CI_ADJACENTES;

INSERT INTO CI_ADJACENTES (
	CI_ID_FACE, 
	COD_MUNICIPIO, 
	CI_ID_QUADRA, 
	SC_ID_LOGRADOURO, 
	CI_COD_UNICO_ENDERECO,
	DIM_ADJACENTE ) 
	SELECT DISTINCT 
			CONCAT(
				LT.COD_MUNICIPIO, ";", LT.NUM_QUADRA, ";", LG.SC_ID_LOGRADOURO
			) AS CI_ID_FACE,
			LT.COD_MUNICIPIO, 
			NUM_QUADRA AS CI_ID_QUADRA, 
			SC_ID_LOGRADOURO,
			COD_UNICO_ENDERECO AS CI_COD_UNICO_ENDERECO, 
			DIM_PROFUNDIDADE AS DIM_ADJACENTE 
		FROM CI_LOTES LT
		JOIN CI_LOGRADOUROS LG 
			ON (LT.NOM_LOGRADOURO_ADJACENTE = LG.CI_NOM_LOGRADOURO)
			AND (LT.COD_MUNICIPIO = LG.COD_MUNICIPIO)
	WHERE (NOM_LOGRADOURO_ADJACENTE <> "")
;

-- Atualizando DIM_FACE
select * from CI_FACES F
INNER JOIN (
    -- Agrupa-se os valores por CI_ID_FACE para evitar múltiplas somas 
    SELECT 
        CI_ID_FACE, 
        SUM(DIM_ADJACENTE) AS TOTAL_ADJACENTE
    FROM CI_ADJACENTES
    GROUP BY CI_ID_FACE
) A ON F.CI_ID_FACE = A.CI_ID_FACE;

SELECT * FROM CI_FACES;






